export const destinations = [
  {
    id: 1,
    name: "Santorini, Greece",
    description: "Iconic white-washed buildings with blue domes overlooking the crystal clear Aegean Sea. Perfect for romance and relaxation.",
    price: 1200,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1613395877344-13d4c79e4df1?auto=format&fit=crop&q=80&w=800",
    tags: ["Romance", "Beach", "History"],
  },
  {
    id: 2,
    name: "Kyoto, Japan",
    description: "Ancient temples, traditional tea houses, and sublime zen gardens. A journey into the heart of Japanese culture.",
    price: 1500,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=800",
    tags: ["Culture", "History", "Nature"],
  },
  {
    id: 3,
    name: "Machu Picchu, Peru",
    description: "The Lost City of the Incas, high in the Andes mountains. A bucket-list adventure for hikers and history buffs.",
    price: 1800,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&q=80&w=800",
    tags: ["Adventure", "Hiking", "History"],
  },
  {
    id: 4,
    name: "Banff, Canada",
    description: "Turquoise lakes, snow-capped peaks, and abundant wildlife in the heart of the Canadian Rockies.",
    price: 1100,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1533052061298-63916960d70b?auto=format&fit=crop&q=80&w=800",
    tags: ["Nature", "Hiking", "Skiing"],
  },
  {
    id: 5,
    name: "Maui, Hawaii",
    description: "Tropical paradise with golden beaches, lush rainforests, and the famous Road to Hana.",
    price: 2000,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1542259679450-1a3978f60383?auto=format&fit=crop&q=80&w=800",
    tags: ["Beach", "Relaxation", "Nature"],
  },
  {
    id: 6,
    name: "Reykjavik, Iceland",
    description: "Gateway to the land of fire and ice. Northern lights, geysers, and stunning waterfalls await.",
    price: 1600,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1476610182048-b716b8518aae?auto=format&fit=crop&q=80&w=800",
    tags: ["Adventure", "Nature", "Cold"],
  },
];

export const popularItineraries = [
  {
    id: 1,
    title: "European Summer Dream",
    duration: "10 Days",
    stops: ["Paris", "Rome", "Barcelona"],
    price: 2500,
    image: "https://images.unsplash.com/photo-1499856871940-a09627c6dcf6?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 2,
    title: "Asian Cultural Immersion",
    duration: "14 Days",
    stops: ["Tokyo", "Seoul", "Bangkok"],
    price: 3000,
    image: "https://images.unsplash.com/photo-1528164344705-47542687000d?auto=format&fit=crop&q=80&w=800",
  },
];
