import { useState } from "react";
import { useRoute, Link } from "wouter";
import { motion } from "framer-motion";
import { MapContainer, TileLayer, Marker, Popup } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import { Download, ArrowLeft, Map as MapIcon, Calendar, DollarSign, History, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { destinations } from "@/lib/mockData";
import { jsPDF } from "jspdf";
import L from 'leaflet';

// Fix Leaflet icon issue
delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon-2x.png',
  iconUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon.png',
  shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-shadow.png',
});

export default function DestinationDetails() {
  const [match, params] = useRoute("/destination/:id");
  const id = parseInt(params?.id);
  const destination = destinations.find(d => d.id === id);

  if (!destination) {
    return <div className="container py-20 text-center">Destination not found</div>;
  }

  const handleDownload = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(24);
    doc.setTextColor(0, 102, 102); // Primary color
    doc.text(destination.name, 20, 20);
    
    // Subheader
    doc.setFontSize(14);
    doc.setTextColor(100, 100, 100);
    doc.text(`${destination.country} - Travel Guide`, 20, 30);
    
    // Description
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const splitDesc = doc.splitTextToSize(destination.fullDescription, 170);
    doc.text(splitDesc, 20, 45);
    
    // Details
    let yPos = 80;
    doc.setFontSize(16);
    doc.setTextColor(0, 102, 102);
    doc.text("Key Information", 20, yPos);
    
    yPos += 10;
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Currency: ${destination.currency}`, 20, yPos);
    doc.text(`Estimated Daily Cost: $${destination.dailyCost}`, 20, yPos + 10);
    doc.text(`Rating: ${destination.rating}/5.0`, 20, yPos + 20);
    
    yPos += 40;
    doc.setFontSize(16);
    doc.setTextColor(0, 102, 102);
    doc.text("Top Attractions", 20, yPos);
    
    yPos += 10;
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    destination.attractions.forEach((spot, i) => {
      doc.text(`• ${spot.name} (${spot.type})`, 20, yPos + (i * 10));
    });

    yPos += 50;
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Velara Travel Genie Pro", 20, 280);

    doc.save(`${destination.name.replace(/\s+/g, '_')}_Guide.pdf`);
  };

  return (
    <div className="pb-20">
      {/* Hero Header */}
      <div className="relative h-[60vh] w-full">
        <img 
          src={destination.image} 
          alt={destination.name} 
          className="w-full h-full object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-background to-transparent" />
        <div className="absolute bottom-0 left-0 right-0 container mx-auto px-4 pb-12">
          <Link href="/explore">
            <Button variant="ghost" className="text-white mb-6 hover:bg-white/20">
              <ArrowLeft className="mr-2 h-4 w-4" /> Back to Explore
            </Button>
          </Link>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
          >
            <div className="flex flex-wrap gap-2 mb-4">
              {destination.tags.map(tag => (
                <Badge key={tag} variant="secondary" className="bg-white/20 hover:bg-white/30 text-white border-none">
                  {tag}
                </Badge>
              ))}
            </div>
            <h1 className="text-5xl md:text-7xl font-display font-bold text-white mb-4">
              {destination.name}
            </h1>
            <div className="flex items-center gap-6 text-white/90">
              <span className="flex items-center gap-2">
                <Star className="w-5 h-5 text-yellow-400 fill-yellow-400" />
                {destination.rating} Rating
              </span>
              <span className="flex items-center gap-2">
                <DollarSign className="w-5 h-5" />
                Approx. ${destination.dailyCost}/day
              </span>
            </div>
          </motion.div>
        </div>
      </div>

      <div className="container mx-auto px-4 -mt-8 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-8">
            <Card className="border-none shadow-xl">
              <CardContent className="p-8 space-y-6">
                <div className="flex justify-between items-center">
                  <h2 className="text-3xl font-bold">Overview</h2>
                  <Button onClick={handleDownload} className="gap-2 bg-primary hover:bg-primary/90">
                    <Download className="w-4 h-4" /> Download Guide (PDF)
                  </Button>
                </div>
                <p className="text-lg text-muted-foreground leading-relaxed">
                  {destination.fullDescription}
                </p>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-6">
                  <div className="bg-muted/30 p-6 rounded-xl space-y-3">
                    <h3 className="font-semibold flex items-center gap-2">
                      <History className="w-5 h-5 text-primary" /> History
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      {destination.history}
                    </p>
                  </div>
                  <div className="bg-muted/30 p-6 rounded-xl space-y-3">
                    <h3 className="font-semibold flex items-center gap-2">
                      <DollarSign className="w-5 h-5 text-green-600" /> Currency & Costs
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      <strong>Currency:</strong> {destination.currency}
                    </p>
                    <p className="text-sm text-muted-foreground">
                      <strong>Daily Budget:</strong> ${destination.dailyCost} (avg)
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="border-none shadow-xl overflow-hidden">
              <div className="h-[400px] w-full relative z-0">
                 <MapContainer 
                   center={destination.coordinates} 
                   zoom={13} 
                   style={{ height: '100%', width: '100%' }}
                   scrollWheelZoom={false}
                 >
                   <TileLayer
                     attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
                     url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                   />
                   <Marker position={destination.coordinates}>
                     <Popup>
                       {destination.name}
                     </Popup>
                   </Marker>
                 </MapContainer>
              </div>
            </Card>
          </div>

          {/* Sidebar */}
          <div className="space-y-6">
            <Card className="border-none shadow-lg bg-primary text-white">
              <CardContent className="p-6">
                <h3 className="text-xl font-bold mb-4">Top Attractions</h3>
                <ul className="space-y-4">
                  {destination.attractions.map((spot, i) => (
                    <li key={i} className="flex items-center gap-3 bg-white/10 p-3 rounded-lg">
                      <div className="w-8 h-8 rounded-full bg-white text-primary flex items-center justify-center font-bold text-sm">
                        {i + 1}
                      </div>
                      <div>
                        <p className="font-semibold">{spot.name}</p>
                        <p className="text-xs text-white/70">{spot.type}</p>
                      </div>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            <Card className="border-none shadow-lg">
              <CardContent className="p-6 space-y-4 text-center">
                <h3 className="text-xl font-bold">Ready to go?</h3>
                <p className="text-muted-foreground text-sm">
                  Add this destination to your itinerary to start planning details.
                </p>
                <Link href="/itinerary">
                  <Button className="w-full" variant="outline">Add to Itinerary</Button>
                </Link>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}
